### ISSUE TITLE
Enhancement/Feature Request - Archive Old Saves

### ISSUE THREAD

**Issue by zer0Kerbal** [linuxgurugamer/BetterLoadSaveGame#3]
@linuxgurugamer 
## per the stream:
zer0Kerbal: mod addition : archive old saves
zer0Kerbal: which would move saves older than x into .zip (deleting original)
zer0Kerbal: I agree. and will. (.this)
zer0Kerbal: not priority and yes, is complicated.

**Comment by hngdog** [comment]
Or, just allow a filter, x time passed, just don't show them?
Or maybe do something like Time Machine on the Mac, reduce them down to weekly when older than a month?

**Comment by linuxgurugamer** [comment]
@hngdog In a perfect world, with plenty of free time, sure.  But every time I have to add something, it takes a lot of time to write and test.  Requests need to be reasonable.  Time machine is nice, but the code behind it which may seem simple, would probably have some gotcha's which I really dont want to deal with.

**Comment by linuxgurugamer** [comment]
@zer0Kerbal  @hngdog 
Question for both of you:

The following options aren't difficult to do:

- Delete files older than X
- Archive files older than X

where X can be:

- hours
- days

Also:

- Keep X most recent saves, delete others
- Keep X most recent saves, archive others

To avoid complexity, archiving will mean to move into subdirectory, but will NOT compress.
The question now becomes, when to run this.  The following occurs to me:

1. At game startup (entering game from MainMenu)
2. Upon request via button
3. Anytime entering BLSG menu

Your opinion counts, please let me know your preference, or another other ideas

Edit:  I originally had "minutes" as a unit, but deleted it since it would just add confusion

**Comment by linuxgurugamer** [comment]
No responses, so I did what I thought was good.
Released

**Comment by hngdog** [comment]
Looks good. I noticed that if you have not archived anything yet, it logs an error looking for the archive folder that doesn’t exist yet.


Sent from my cassette tape

Pete

**Comment by linuxgurugamer** [comment]
Yes, but it should create it if it doesn't exist.
If it doesn't, please confirm
